#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 6d34f12b-cd29-4c1a-a574-cd557bd60098
# Source File: C:\Sander\Scripts\Powershell\PrimalScript\App01\App01.psproj
#------------------------------------------------------------------------
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2017 v5.4.139
     Generated on:       28-4-2017 07:38
     Generated by:       sander
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2017
#>



#region Source: Startup.pss
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
[void][Reflection.Assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
[void][Reflection.Assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
[void][Reflection.Assembly]::Load('System.DirectoryServices, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main {
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
		
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)
	
	
	#--------------------------------------------------------------------------
	
	if((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}







#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	
	#Sample function that provides the location of the script
	function Get-ScriptDirectory
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	#Sample variable that provides the location of the script
	[string]$ScriptDirectory = Get-ScriptDirectory
	
	
	
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$frmLoop = New-Object 'System.Windows.Forms.Form'
	$tbBeginAt = New-Object 'System.Windows.Forms.TextBox'
	$lblBeginAt = New-Object 'System.Windows.Forms.Label'
	$lblSubloop = New-Object 'System.Windows.Forms.Label'
	$lblMasterloop = New-Object 'System.Windows.Forms.Label'
	$tbSubloop = New-Object 'System.Windows.Forms.TextBox'
	$buttonOK = New-Object 'System.Windows.Forms.Button'
	$tbMasterloop = New-Object 'System.Windows.Forms.TextBox'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$frmLoop_Load={
		#TODO: Initialize Form Controls here
	
	}
	
	$btn01_Click={
		#TODO: Place custom script here
		write-host $tbMasterloop.Text
		write-host $tbSubloop.Text
		$MasterLoop = $tbMasterloop.Text
		$SubLoop = $tbSubloop.Text
		[int]$BeginAt = $tbBeginAt.Text #Numering starts at this number
		
		#BEGIN This apply's to the $i (Masterloop)
		if ($BeginAt)
		{
			write-host "MasterLoop ($MasterLoop) x SubLoop ($subloop)" -ForegroundColor Green
			$i = $BeginAt
			$MasterLoop = ($BeginAt + $MasterLoop) - 1
			write-host "BeginAt:"$i -ForegroundColor Green
			[system.Windows.Forms.MessageBox]::show("Begin at: $i", "Info",
			[system.Windows.Forms.MessageBoxButtons]::OK,
			[system.Windows.Forms.MessageBoxIcon]::Information)
		}
		else
		{
			$i = 1
			write-host "No BeginAt value entered, beginning at default of " $i
			[system.Windows.Forms.MessageBox]::show("No BeginAt value entered, beginning at default of $i", "Info",
			[system.Windows.Forms.MessageBoxButtons]::OK,
			[system.Windows.Forms.MessageBoxIcon]::Information)
		}
		#END This apply's to the $i (Masterloop)
		
		
		for ($i; $i -le $MasterLoop; $i++)
		{
			#This apply's to the $i ($AppIDNrMasterLoop).
			for ($j = 1; $j -le $SubLoop; $j++)
			{
				#Write information to file
				write-host "MasterLoop:nr:$i SubLoop:nr:$j"
				[system.Windows.Forms.MessageBox]::show("MasterLoop:nr:$i SubLoop:nr:$j","Info",
				[system.Windows.Forms.MessageBoxButtons]::OK,
				[system.Windows.Forms.MessageBoxIcon]::Information)
			}
		}
	}
	
		# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$frmLoop.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_tbBeginAt = $tbBeginAt.Text
		$script:MainForm_tbSubloop = $tbSubloop.Text
		$script:MainForm_tbMasterloop = $tbMasterloop.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonOK.remove_Click($btn01_Click)
			$frmLoop.remove_Load($frmLoop_Load)
			$frmLoop.remove_Load($Form_StateCorrection_Load)
			$frmLoop.remove_Closing($Form_StoreValues_Closing)
			$frmLoop.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$frmLoop.SuspendLayout()
	#
	# frmLoop
	#
	$frmLoop.Controls.Add($tbBeginAt)
	$frmLoop.Controls.Add($lblBeginAt)
	$frmLoop.Controls.Add($lblSubloop)
	$frmLoop.Controls.Add($lblMasterloop)
	$frmLoop.Controls.Add($tbSubloop)
	$frmLoop.Controls.Add($buttonOK)
	$frmLoop.Controls.Add($tbMasterloop)
	$frmLoop.AutoScaleDimensions = '6, 13'
	$frmLoop.AutoScaleMode = 'Font'
	$frmLoop.ClientSize = '212, 292'
	$frmLoop.Name = 'frmLoop'
	$frmLoop.Text = 'Loop'
	$frmLoop.add_Load($frmLoop_Load)
	#
	# tbBeginAt
	#
	$tbBeginAt.ForeColor = 'WindowText'
	$tbBeginAt.Location = '51, 148'
	$tbBeginAt.Name = 'tbBeginAt'
	$tbBeginAt.Size = '100, 20'
	$tbBeginAt.TabIndex = 3
	$tbBeginAt.Text = '1'
	#
	# lblBeginAt
	#
	$lblBeginAt.AutoSize = $True
	$lblBeginAt.ForeColor = 'Red'
	$lblBeginAt.Location = '51, 132'
	$lblBeginAt.Name = 'lblBeginAt'
	$lblBeginAt.Size = '44, 13'
	$lblBeginAt.TabIndex = 0
	$lblBeginAt.Text = 'BeginAt'
	#
	# lblSubloop
	#
	$lblSubloop.AutoSize = $True
	$lblSubloop.Location = '51, 76'
	$lblSubloop.Name = 'lblSubloop'
	$lblSubloop.Size = '46, 13'
	$lblSubloop.TabIndex = 0
	$lblSubloop.Text = 'Subloop'
	#
	# lblMasterloop
	#
	$lblMasterloop.AutoSize = $True
	$lblMasterloop.Location = '51, 26'
	$lblMasterloop.Name = 'lblMasterloop'
	$lblMasterloop.Size = '59, 13'
	$lblMasterloop.TabIndex = 0
	$lblMasterloop.Text = 'Masterloop'
	#
	# tbSubloop
	#
	$tbSubloop.Location = '51, 93'
	$tbSubloop.Name = 'tbSubloop'
	$tbSubloop.Size = '100, 20'
	$tbSubloop.TabIndex = 2
	$tbSubloop.Text = '2'
	#
	# buttonOK
	#
	$buttonOK.DialogResult = 'OK'
	$buttonOK.Location = '76, 192'
	$buttonOK.Name = 'buttonOK'
	$buttonOK.Size = '75, 23'
	$buttonOK.TabIndex = 4
	$buttonOK.Text = '&OK'
	$buttonOK.UseVisualStyleBackColor = $True
	$buttonOK.add_Click($btn01_Click)
	#
	# tbMasterloop
	#
	$tbMasterloop.Location = '51, 43'
	$tbMasterloop.Name = 'tbMasterloop'
	$tbMasterloop.Size = '100, 20'
	$tbMasterloop.TabIndex = 1
	$tbMasterloop.Text = '3'
	$frmLoop.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $frmLoop.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$frmLoop.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$frmLoop.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$frmLoop.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $frmLoop.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
